### ISSUE TITLE
Export is mis-named? or README is misleading?

### ISSUE THREAD

**Issue by xml** [sarifmiaa/capacitor-device-locale#3]
Hi! Thanks for this plugin, which I'm excited to try. 

On my initial attempt, I hit the following: 
`Attempted import error: 'getDeviceLocale' is not exported from 'capacitor-device-locale' (imported as 'getDeviceLocale').`

Whereas the only thing I can find exported, anywhere in the JS, is `exports.Device = Device;`. If I try to import that, it seems to work. 

Am I reading that right, or overlooking something? 

(FWIW, the main export from `@capacitor/device` is called `Device`, so in an ideal world, this package would indeed export as `getDeviceLocale`, to disambiguate.)

**Comment by sarifmiaa** [comment]
@xml  Thank you for bringing this to my attention 👁️ . The README was not updated, but I have now corrected it with the right usage information.
